### ISSUE TITLE
Host documentation on readthedocs

### ISSUE THREAD

**Issue by huard** [bird-house/birdhouse-deploy#113]
There does not seem to be a readthedocs link for the documentation.

**Comment by Zeitsperre** [comment]
This is done https://readthedocs.org/projects/birdhouse-deploy/. Do we want to style it in any way? I can copy over the theme from another project pretty quickly.

**Comment by huard** [comment]
I  suggest the standard readthedocs theme

**Comment by Zeitsperre** [comment]
@huard Is this good to close with #118?
