### ISSUE TITLE
[Feature] Add a bird that allows for loose coupling between components while keeping them in synch

### ISSUE THREAD

**Issue by dbyrns** [bird-house/birdhouse-deploy#120]
This use case became obvious with the fact that a lot of components needs to be aware and configured when a new user is created.
Magpie handles those users, but we don't want it to be tighly-coupled with other components.
Magpie has also the ability to notify whoever registers a hook, but we don't want other components to be tighly-coupled to the Magpie hook neither.
Here comes Cowbird (a bird that lays in the nests of other birds), who will be able to register a hook in Magpie and do whatever is necessary for all the components in needs when it is notify.  
With this paradigm, we can do a lot of things : 

- When a user is created, workspace will be created in geoserver, thredds and jupyterhub
- When a user is deleted a cleanup will be performed
- When new data is added (via the ingestion service, a process output or a user notebook), a monitoring sub-system will be able to update components in needs.
- For ressources being served by more than one services, a permissions synchronizer will be able to keep them aligned across services.

Here we got a preliminary design : 
![Cowbird Components 1 2 0](https://user-images.githubusercontent.com/4202336/106329921-4e918f00-6250-11eb-99b3-202fde0c38cb.png)

**Comment by dbyrns** [comment]
Hi @cehbrecht, we want to share with you our plan to add another bird in the PAVICS stack to help us synchronize states between components. Any comments would be welcomed.

**Comment by fmigneault** [comment]
for reference: 
https://github.com/Ouranosinc/cowbird/pull/1
