### ISSUE TITLE
Specify license

### ISSUE THREAD

**Issue by huard** [bird-house/birdhouse-deploy#140]
There is no license that accompany the code.

**Comment by Zeitsperre** [comment]
@huard @cehbrecht Apache v2 is the standard we've used the Ouranos side to ensure no one uses our logos. Is there a convention for Birdhouse? (GPL?)

**Comment by huard** [comment]
Unless there is an objection, let's go with Apache v2 then.

**Comment by tlvu** [comment]
Dupe of https://github.com/bird-house/birdhouse-deploy/issues/309
