### ISSUE TITLE
Build and deploy intake catalogs

### ISSUE THREAD

**Issue by huard** [bird-house/birdhouse-deploy#148]
Build and deploy intake catalogs from pavics-vdb

- [ ] Should be be triggered on merge or tag ?
- [ ] Where should the catalogs live ? pavics.ouranos.ca/catalogs/ ? pavics.ouranos.ca/intake

Intake catalogs are our interim solution until STAC is more mature. So maybe we should reserve /catalog for the future.

**Comment by tlvu** [comment]
@huard 

Fixed in PR https://github.com/bird-house/birdhouse-deploy-ouranos/pull/14

Sorry did not realized there was this issue opened.

> Should be be triggered on merge or tag ?

Triggered on merge to `master` branch.

> Where should the catalogs live ? pavics.ouranos.ca/catalogs/ ? pavics.ouranos.ca/intake
> Intake catalogs are our interim solution until STAC is more mature. So maybe we should reserve /catalog for the future.

Currently it's under https://pavics.ouranos.ca/catalog.  Can easily be changed for /intake, let me know.
