### ISSUE TITLE
:bug: [BUG]: Silent error when  EXTRA_CONF_DIRS is invalid

### ISSUE THREAD

**Issue by aulemahal** [bird-house/birdhouse-deploy#266]
When adding  a directory to EXTRA_CONF_DIRS, if there is a typo in its name, the error goes unnoticed.

Feel free to close this if not important enough, but I felt that it would be nice if `pavics-compose.sh` would fail when encountering an invalid directory name.

**Comment by tlvu** [comment]
We do not validate those dirs because all the files (docker-compose-extra.yml, default.env) under those dirs are optional, but probably we need to validate the dir itself, without validating the files under.
