### ISSUE TITLE
:bulb: [Feature] Consider official GeoServer Docker

### ISSUE THREAD

**Issue by fmigneault** [bird-house/birdhouse-deploy#315]
## Description

We've been using the https://hub.docker.com/r/kartoza/geoserver/tags with our own re-releases https://hub.docker.com/repository/docker/pavics/geoserver/tags to mitigate inconsistent release tags described in https://github.com/kartoza/docker-geoserver/issues/233.

The official https://github.com/geoserver/docker is now more actively maintained, and images are published openly here:
https://geoserver-docker.osgeo.org/#browse/browse:docker:v2%2Fgeoserver%2Ftags%2F2.22.2

It might be worth considering if those references would be good candidates to replace kartoza-based releases.

## References

see description

## Concerned Organizations

- all using GeoServer

**Comment by tlvu** [comment]
I am not sure why at the beginning the kartoza Geoserver image was chosen but current I think the kartoza image is still better for the fact that all plugins are pre-download and bundled with the docker image, which gives us 100% reproductibility.

The official Geoserver image will download the plugins at container startup only.  Not only this is less reproducible, it will also slow down the startup.

So kartoza have this problem https://github.com/kartoza/docker-geoserver/issues/233 that is annoying but we also have an easy work-around, we just cached their image ourself.

Let me know if I can close this issue as won't fix.

**Comment by fmigneault** [comment]
As long as the applied image is rebuilt and updated often enough (e.g.: to resolve #320), I don't have any objection about which reference is used.
