### ISSUE TITLE
:bulb: [Feature] Protect Portainer

### ISSUE THREAD

**Issue by fmigneault** [bird-house/birdhouse-deploy#335]
## Description

Ensure Portainer is accessed behind Magpie/Twticher authentication/authorization. 
Currently, it uses its own authentication mechanism.
It could be aligned with Magpie/Twitcher, or have a double-authentication layer.
Either way, it should be limited to admin-only access.

## References

- https://github.com/bird-house/birdhouse-deploy/pull/331#discussion_r1210542987

**Comment by tlvu** [comment]
I think @mishaschwartz is dropping this one so can close this issue?

**Comment by tlvu** [comment]
@mishaschwartz opps I vaguely remember you deprecated portainer with all the other (catalog, solr, frontend, ...)?  Sorry if my memory is wrong.  I have too much on my plate lately.

**Comment by fmigneault** [comment]
This was resolved in https://github.com/bird-house/birdhouse-deploy/pull/331
