### ISSUE TITLE
Canarie Solr monitoring not working on staging system

### ISSUE THREAD

**Issue by tlvu** [bird-house/birdhouse-deploy#6]
Migration from old PAVICS https://github.com/Ouranosinc/PAVICS/issues/207

This is because the staging system do not have the same data as the production system.

Could we change this query to some data that will minimally exist on all PAVICS deployment of all organizations, like https://github.com/Ouranosinc/pavics-sdi/issues/147 https://github.com/Ouranosinc/PAVICS/blob/dd0eefb584724e720ccb3efa648f6b42d43d6f70/birdhouse/config/canarie-api/docker_configuration.py.template#L81-L88

This error is the only one that fail canarie monitoring on staging server:
![2020-01-09-132100_921x778_scrot](https://user-images.githubusercontent.com/11966697/72094086-9ced8c00-32e3-11ea-9939-5bd4fe3fc926.png)

If Canarie monitoring pass on staging servers, then we can have this https://github.com/Ouranosinc/PAVICS/issues/186.

Big win because we get notification when new deployment is broken on staging system so we can react faster to not break the production system.

**Comment by tlvu** [comment]
@huard @tlogan2000 can you guys suggest a minimum and small test dataset to be include in all Thredds so the Solr query works for all PAVICS deployment, not just our production one?

**Comment by huard** [comment]
testdata ?

**Comment by tlvu** [comment]
> testdata ?

Is that minimal enough or can be made smaller?  All public data, no legal issues? I would like to copy these data automatically on all PAVICS deployment.

**Comment by huard** [comment]
You're right, probably too big and unclear about licensing issues. If you want to make some progress quickly, a quick fix would be testdata/flyingpigeon/{cordex, cmip3, cmip5}.

**Comment by tlvu** [comment]
@huard @tlogan2000 @Zeitsperre 

@MatProv from CRIM is working on an automated testing pipeline that would spin up a new fresh VM with a full PAVICS deployment.

Given it's a fresh VM each time, it's missing all the test data, which breaks our Jenkins notebook testsuite.

So this issue about minimising the number and size of test data required on Thredds so they can be repeatly replicated on fresh VM is now blocking him.  There is also a question about legal issue of those test data that will have to be replicated to All PAVICS deployments.

Now that I think about it, we'll need Geoserver testdata as well.  What's the size, how to reduce the size, how to load them without using Geoserver webUI !

So I've given a quick work-around to Mathieu to unblock him but we'll need to work on this test data issue sooner than later.

Work-around given to Mathieu:

* For each notebook, any input data from Thredds or Geoserver, change the hostname from `pavics.ouranos.ca` to `boreas.ouranos.ca` to avoid Jenkins from changing it to the PAVICS host under test.  Basically instead of using the test data on the PAVICS host under test, use from our Boreas.
  * This is far from ideal because it means the Thredds, Geoserver and Magpie permissions for Thredds and Geoserver is not tested on the PAVICS host under test.  But at least it will let Jenkins test the rest of the WPS services (also behind Magpie permissions).

* Impact several repos that Jenkins is pulling notebooks from (Pavics-sdi, Finch, Raven).  Mathieu will have to update all those notebooks.

Anyone against or see additional problems with this work-around?

**Comment by tlogan2000** [comment]
We should be able create a set of 'random data' netcdf files (even relatively large matrices) with xarray relatively easily.  We can add appropriate attributes based on current test data links etc... but data itself is 'fake' therefore no licence issues.

**Comment by tlvu** [comment]
> We should be able create a set of 'random data' netcdf files (even relatively large matrices) with xarray relatively easily. We can add appropriate attributes based on current test data links etc... but data itself is 'fake' therefore no licence issues.

This would solve a lot of problems indeed, awesome idea !  Those notebooks used to run tests are also used as tutorial notebooks, hopefully not impacting ease of reading when used as tutorial.

We then only need 1 single `.nc` file, can be a dummy one, synced across all PAVICS, just to test Thredds capabilities and Magpie permissions on top of Thredds.  Or this dummy file can also be generated so no sync is required.  The point is we still need to test that Thredds can serve data properly behind Magpie/Twitcher.

**Comment by tlogan2000** [comment]
If not testing any calculations or values actually in the file (ie. you just need a functional .nc) we can generate on the fly most likely

**Comment by tlogan2000** [comment]
`xarray`  is part of the test env i'm assuming?

**Comment by tlvu** [comment]
> If not testing any calculations or values actually in the file (ie. you just need a functional .nc) we can generate on the fly most likely

Oh good point.  Those are also used as tutorial notebooks, I guess we would want to do some real calculations in there, for some of the notebooks.  I do not fully understand those notebooks so can not give a better answer sorry.

> `xarray` is part of the test env i'm assuming?

Yes it is since we install `xclim` into our Jupyter env, which also serve as Jenkins runtime environment so we guaranty the Jupyter env can run those notebooks.

**Comment by Zeitsperre** [comment]
> Now that I think about it, we'll need Geoserver testdata as well. What's the size, how to reduce the size, how to load them without using Geoserver webUI !

This is a bit complicated, as the datasets are numerous, in a bunch of different formats and _might_ have licensing issues preventing us from turning them into images (I doubt it, but I've never verified).

There's a tool we used several years ago for managing the data housed in the GeoServer (https://github.com/planetfederal/gsconfig) but this looks to be abandoned now (also only supported Python2). The maintainers suggest this fork instead (https://github.com/GeoNode/geoserver-restconfig). We'd need to do some research into creating some workflows that perform the data updates we want during image creation. The documentation doesn't adequately state whether creating workspaces/stores is supported.

If we were to store all feature data for the GeoServer in its Postrgres database, creating a backup image of that might be an option that prevents us from having a bunch of shapefiles scattered everywhere?

Before I look into any of this, can you confirm that this is what you mean? I haven't actually worked on the PAVICS stack/GeoServer in a long time, so I'm not certain how much of this process has already been automated at this point.

**Comment by tlvu** [comment]
@Zeitsperre got it. I am discussing with @MatProv to find the least effort option that still unblock him.  I can provide work-around to buy time for us to think this through properly.  How much "easy" we want all other PAVICS deployment to be able to run our Jenkins test suite.

**Comment by tlogan2000** [comment]
```
import numpy as np
import xarray as xr
time1 = xr.cftime_range(start='1971-01-01',end='2000-12-31', calendar='standard')
resolution = 0.25
lon = xr.DataArray(np.arange(-80, -60, resolution), dims=['lon'])
lat = xr.DataArray(np.arange(45, 50, resolution), dims = ['lat'])
var1 = xr.DataArray(np.random.random((len(time1), len(lat), len(lon))),
                    dims=['time','lat','lon']).assign_coords(dict(time=time1, lat=lat, lon=lon))
ds = xr.Dataset(data_vars=None, coords=dict(time=time1, lat=lat, lon=lon))
ds['test_variable'] = var1
ds.to_netcdf('test.nc')
```

**Comment by tlogan2000** [comment]
@tlvu @MatProv  example of creating a random netcdf.  If we need to add fake attributes for the tests etc let me know.  

Feel free to play with size of the array ... here we have 30 years at .25 degree spatial resolution but up to you to decide

**Comment by tlogan2000** [comment]
````
import numpy as np
import xarray as xr

np.random.seed(42)
time1 = xr.cftime_range(start='1971-01-01',end='2000-12-31', calendar='standard')
resolution = 0.25
lon = xr.DataArray(np.arange(-80, -60, resolution), dims=['lon'])
lat = xr.DataArray(np.arange(45, 50, resolution), dims = ['lat'])

attrs = dict(units="K",
standard_name="air_temperature",
long_name="daily mean temperature",
description="Daily mean temperature",
cell_methods="time: mean within days")

var1 = xr.DataArray(np.random.normal(loc=10, scale=6,size=((len(time1), len(lat), len(lon)))),
                    dims=['time','lat','lon']).assign_coords(dict(time=time1, lat=lat, lon=lon), attrs=attrs)
ds = xr.Dataset(data_vars=None, coords=dict(time=time1, lat=lat, lon=lon))
ds['tas'] = var1
    
ds.to_netcdf('/home/logan/test.nc')
````

Setting random seed and adding a minimum number of attrs should allow notebooks to run I think

**Comment by tlvu** [comment]
I discovered the subset of `.nc` files needed for the automated test suite is a very small subset of our big `testdata` folder.  Experimenting to provide @MatProv directly those files.  @tlogan2000 we might not need to generate dummy files.
