### ISSUE TITLE
Idle Jupyter server cause open file limit exhaustion

### ISSUE THREAD

**Issue by tlvu** [bird-house/birdhouse-deploy#67]
This morning, none of the docker commands was responding because we have exhausted the open file limit on the user that runs the PAVICS platform (the user that does `./pavics-compose.sh up -d`).

```
$ ./pavics-compose.sh ps
-bash: fork: retry: No child processes
-bash: fork: retry: No child processes
-bash: fork: retry: No child processes
-bash: fork: retry: No child processes
-bash: fork: Resource temporarily unavailable
```

The immediate work-around is to increase the soft and hard nofile limit for the corresponding user in `/etc/security/limits.conf` file and apply that new limit immediately `ulimit -n NEW_LIMIT` (`ulimit -n` show the current effective limit).  Find the current number of open file this way `sudo lsof -u $USER|wc -l` and put something higher than that in the `limits.conf` file. Reference https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/5/html/tuning_and_optimizing_red_hat_enterprise_linux_for_oracle_9i_and_10g_databases/chap-oracle_9i_and_10g_tuning_guide-setting_shell_limits_for_the_oracle_user

Then using a different user than the user that usually runs PAVICS because that user can not do anything else and restart the docker daemon (`sudo systemctl restart docker`).  Back to the regular user running PAVICS, ff the containers have problems to restart, destroy them and re-create them from scratch (`./pavics-compose.sh down && sleep 10 && ./pavics-compose.sh up -d`).

For a more permanent solution than keep increasing the limit each time we burst it is to setup culling idle Jupyter server as describe here https://discourse.jupyter.org/t/jupyterhub-doesnt-kill-processes-and-threads-when-notebooks-are-closed-or-user-log-out/2244/2

Also need to add monitoring for open file limit to we are alerted in advance of near exhaustion to avoid having to restart the entire docker daemon.

Ping @moulab88 @tlogan2000 if you guys have anything to add.

Edit:
* add command to see current effective limit and set new limit immediately
* add reference to redhat docs

**Comment by tlogan2000** [comment]
The multilevel culling control could be interesting (as long as I understand it correctly!) .... but it seems like it would be possible to cull individual user kernels that are idle for say a few hours (level 1) and also entire user servers after being idle maybe a few days or even a week say(level 2)?  Can't speak for all deployments but on our end I think we want to give users the chance to run 'long' calculations (level 2 threshold of up to a week) but with the ability to track notebook kernels that are left open accidentally at the same time

**Comment by tlvu** [comment]
Duplicated by https://github.com/Ouranosinc/pavics-sdi/issues/158.

**Comment by tlvu** [comment]
List of built-in metrics exposed by https://github.com/prometheus/node_exporter do not have the file open metric we need.

**Comment by tlvu** [comment]
Triggered this issue again during https://github.com/Ouranosinc/raven/issues/251 with the 25 bogus users logged in, running 1 notebook and stayed logged in for 24 hours.

A weird issue is closing the Jupyter servers for some (6) those 25 test users did not release the open files.

**Comment by tlvu** [comment]
@tlogan2000 Just got this problem again so had to restart the docker daemon.  You might hear complain from Jupyter users.

**Comment by tlvu** [comment]
@tlogan2000 Just got this problem again so had to restart the docker daemon. You might hear complain from Jupyter users.

**Comment by tlvu** [comment]
@tlogan2000 Just got this problem again today March 26 2021 so had to restart the docker daemon. You might hear complain from Jupyter users.

After all the other pending tasks on my plate I would very much like to attack this one.

**Comment by tlvu** [comment]
@tlogan2000 Just got this problem again today June 7 2021 so had to restart the docker daemon. You might hear complain from Jupyter users.

**Comment by tlvu** [comment]
Just got this problem again today July 23 2021 so had to restart the docker daemon.

**Comment by tlvu** [comment]
Documenting system status when this happened on July 23 2021: no CPU spike, below are some active containers:

All containers globally:
![Screenshot 2021-07-23 at 11-44-51 Docker and system monitoring - Grafana](https://user-images.githubusercontent.com/11966697/126808199-71040f27-015c-46b8-910f-e26957a752c9.png)

Geoserver:
![Screenshot 2021-07-23 at 11-45-32 geoserver-Docker and system monitoring - Grafana](https://user-images.githubusercontent.com/11966697/126808219-f5e5460c-fe62-43c1-8fd2-0e65b6198fbc.png)

jupyter-labonte:
![Screenshot 2021-07-23 at 11-46-17 jupyter-labonte-Docker and system monitoring - Grafana](https://user-images.githubusercontent.com/11966697/126808253-4a25f81e-f432-48f6-9d1e-d6a13b76f355.png)

jupyter-lizee:
![Screenshot 2021-07-23 at 11-46-53 jupyter-lizee-Docker and system monitoring - Grafana](https://user-images.githubusercontent.com/11966697/126808276-634105fd-2b67-4910-9c11-27850ae49ffb.png)

**Comment by tlvu** [comment]
FYI @tlogan2000 @moulab88 Just got this problem again today Nov 12 2021 so had to restart the docker daemon.

Documenting system status when this happened:

No spike (Cpu, memory) anywhere in the past 6 hours:

![Screenshot from 2021-11-12 10-11-46](https://user-images.githubusercontent.com/11966697/141493847-49e720b5-9649-4842-afb7-539f58c0f0e3.png)

Memory spike a few days ago (jupyter-logan and jupyter-barbeau):

![Screenshot from 2021-11-12 10-17-50](https://user-images.githubusercontent.com/11966697/141493863-20ffc1b8-aa75-4523-8375-d88444e4b5e8.png)

jupyter-logan memory spike between Nov 9 and Nov 11:

![Screenshot from 2021-11-12 10-22-44](https://user-images.githubusercontent.com/11966697/141493925-414c68f0-c374-4c07-92d8-4757b10a6b9d.png)

jupyter-barbeau memory spike between Nov 8 and Nov 9:

![Screenshot from 2021-11-12 10-23-00](https://user-images.githubusercontent.com/11966697/141493910-d5a6d580-b2a9-4863-8776-961a8c59add8.png)

![Screenshot from 2021-11-12 10-19-19](https://user-images.githubusercontent.com/11966697/141493891-f8face55-6c86-4fb1-889a-d0d036ff768b.png)

**Comment by tlvu** [comment]
Documenting this issue again today Monday 24 January 2022.

So this problem happen again
```
$ docker ps
-bash: fork: retry: No child processes
-bash: fork: retry: No child processes
```

Checking the current open file from another user with sudo:
```
$ sudo lsof -u $PAVICS_USER|wc -l
[sudo] password for admin:
10361
```

Checking the current limits of the current $PAVICS_USER:
```
$ ulimit -n
40960
```

So we have not busted the limit yet or the command to find the current open file is not complete

@moulab88 any extra ideas?

@tlogan2000 FYI

**Comment by tlvu** [comment]
@moulab88 made the "max user processes" change permanent upon reboot:

```
$ cat /etc/security/limits.d/20-nproc.conf 
# Default limit for number of user's processes to prevent
# accidental fork bombs.
# See rhbz #432903 for reasoning.

*          soft    nproc     4096
root       soft    nproc     unlimited
PAVICS_USER     soft    nproc     <higher limit than 4096>
PAVICS_USER     hard    nproc     <higher limit than 4096>

```
