### ISSUE TITLE
Replace ncWMS2 by THREDDS WMS service

### ISSUE THREAD

**Issue by tlvu** [bird-house/birdhouse-deploy#9]
Migrated from old PAVICS https://github.com/Ouranosinc/PAVICS/issues/167, had lots of discussion, summarize below.

Find where in the platform links to the ncWMS2 are used and replaced them with links to the THREDDS WMS service.

Related to https://github.com/Ouranosinc/PAVICS/issues/108

Need more testing to be confident Thredds WMS can replace ncwms2 both in terms of integration with the rest of the components and performance before we pull the plug on ncwms2.

**Comment by huard** [comment]
@tlvu This is done, correct ?

**Comment by tlvu** [comment]
If my memory is correct, we have activagted WMS service on Thredds but we still keep the old ncWMS2 service running while we slowly convert all the tutorial noteoboks to use the new WMS from Thredds?

Let me find the PR that activated WMS on Thredds, maybe there is a note left behind.

**Comment by huard** [comment]
I think the only notebook using WMS is already hitting thredds for WMS: https://pavics-sdi.readthedocs.io/en/latest/notebooks/rendering.html#Gridded-Data-Renderer

**Comment by tlvu** [comment]
I finally traced the PR that activated WMS, it was in the old PAVICS repo: https://github.com/Ouranosinc/PAVICS/pull/161 no mention about what to do next with the duplicate ncWMS.

Have we observed any integration and performance difference with ncWMS?  If not I guess we can pull the plug on ncWMS.

**Comment by huard** [comment]
I think THREDDS uses ncwms internally ; ) https://github.com/Unidata/thredds/issues/234 so it should be pretty much the same.

**Comment by tlvu** [comment]
Should be fixed by https://github.com/bird-house/birdhouse-deploy/pull/311
